repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: check-npm-lockfile
        name: Check npm lockfile
        entry: npm ci --dry-run
        language: system
        files: ^package\.json$
        pass_filenames: false
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.57.1
    hooks:
      - id: eslint
        files: ^.*\.(js|jsx|ts|tsx)$
        exclude: ^node_modules/
        additional_dependencies:
          - eslint@^8.57.1
          - '@eslint/js@^9.31.0'
          - '@typescript-eslint/eslint-plugin@^6.21.0'
          - '@typescript-eslint/parser@^6.21.0'
          - eslint-plugin-react@^7.37.5
          - eslint-plugin-react-hooks@^4.6.2

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: ^.*\.(js|jsx|ts|tsx|json|css|md)$
        exclude: ^node_modules/
        additional_dependencies:
          - prettier@^3.0.0
